### ISSUE TITLE
Hyperbolic to Exponential Model Doesn't Transition To Exponential When Using Days

### ISSUE THREAD

**Issue by adamcagle** [derrickturk/aRpsDCA#2]
> #This calculation works correctly
> years <- hyp2exp.transition(as.nominal(0.85), 1.5, as.nominal(0.05))
> years
[1] 12.64574
> days <- years * 365
> days
[1] 4615.695
> #However, when we switch units from years to days the calculation no longer works
> days <- hyp2exp.transition(as.nominal(0.85, from.period = "year", to.period = "day"), 1.5, as.nominal(0.05, from.period = "year", to.period = "day"))
> days
[1] Inf

**Comment by derrickturk** [comment]
@adamcagle Good catch! The function internally uses a threshold (EXPONENTIAL_EPS) to reject "invalidly small" declines; this threshold was set to a rather large value under the assumption that declines would always be yearly. EXPONENTIAL_EPS will be reduced to a value that permits plausible use with daily nominal rates in the next release.

**Comment by adamcagle** [comment]
Thanks, Derrick. I figured out a workaround, so I'm good to go in the meantime. And thanks for creating this package. I get a lot of use out of it.
