### ISSUE TITLE
from.interval not working?

### ISSUE THREAD

**Issue by aminfardi** [derrickturk/aRpsDCA#7]
Hello,

I am trying to fit an exponential decline to only the last 3 years of production data (i.e. not from time zero) using the best.exponential.from.interval, and setting the argument t.begin = as.numeric(ymd("2014-12-31")), but it generates the following error:

Error in if (D == 0) qi * t else qi/D * (1 - exp(-D * t)): missing value where TRUE/FALSE needed
Traceback:

1. best.exponential.from.interval(q, as.numeric(pad_prod$"Production Date"), 
 .     t.begin = as.numeric(ymd("2014-12-31")))
2. nlminb(c(volume[1]/(t[1] - t.begin), -((volume[2] - volume[1])/volume[1])/(t[2] - 
 .     t[1])), function(guess) sse(volume, diff(exponential.Np(guess[1], 
 .     guess[2], c(t.begin, t)))), lower = lower, upper = upper)
3. objective(.par, ...)
4. sse(volume, diff(exponential.Np(guess[1], guess[2], c(t.begin, 
 .     t))))
5. diff(exponential.Np(guess[1], guess[2], c(t.begin, t)))
6. exponential.Np(guess[1], guess[2], c(t.begin, t))

The workaround for this is to create a normalized time column so my time for the fit always starts at 0, instead of as.numeric dates. Not sure if I am using the from.interval as intended? In my mind, the interval method should achieve the result without the normalized time workaround.

**Comment by derrickturk** [comment]
The workaround is correct and necessary. The interpretation of the `t.begin` argument to the `*.interval` functions is the time (relative to start of production) at which the first interval begins. In other words, all times are interpreted as “normalized time” in aRpsDCA.

**Comment by aminfardi** [comment]
Understood, thanks for continuing to support this great package!
